# Generated by Django 4.1.4 on 2023-08-25 15:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='asset_assigned',
            new_name='AssetAssigned',
        ),
    ]
